### ISSUE TITLE
Holonomic robot tracking the reference path and avoiding moving obstacle

### ISSUE THREAD

**Issue by ZongyuanShen** [nicolapiccinelli/libmpc#11]
Hi,

Thanks for the amazing project. Now, I am trying to implement this library for a holonomic robot (i.e., only consider x y and no velocity and acceleration constaint) to 

1. track a reference path (a set of 2D points with x and y value)
2. avoid moving obstacle (each obstacle has x and y value which could change over time)

I read the tutorial and can not figure out how to implement part 2. Could you let me know how to implement the obstacle avoidance constraint? Thank you very much.

**Comment by nicolapiccinelli** [comment]
Hey @ZongyuanShen thanks a lot! It’s nice to see my project be useful across the community :)

Regarding your question: the choice of how to implement time variant constraints on the state space depends on the MPC type you are trying to implement. For the nonlinear case, you have the freedom to define the constraints as an anonymous function. If you are in the linear case you have to encode them into the box constraints on x or y. 

If you can provide me some more details I can give you a more focused hint. I’m also planning to improve the doc, so any improvement is welcome.
