### ISSUE TITLE
Does the library support real-time iteration mpc scheme?

### ISSUE THREAD

**Issue by abdelhakim96** [nicolapiccinelli/libmpc#16]
Does the libmpc support real-time iteration mpc scheme, like acados library for example? If not, is extending it to support RTI possible?

**Comment by nicolapiccinelli** [comment]
What does it means real time iteration?

**Comment by abdelhakim96** [comment]
"The scheme allows a fast reaction to disturbances by delivering approximations of the exact optimal feedback control which are iteratively refined during the runtime of the controlled process."

This method is applied in acados mpc library https://docs.acados.org/about_acados/index.html


reference to method:
https://epubs.siam.org/doi/abs/10.1137/S0363012902400713?journalCode=sjcodc

**Comment by nicolapiccinelli** [comment]
Hello @abdelhakim96, the library uses SLSQP to solve the underlying non-linear optimization problem. However, it is possible to plan to extend the non-linear optimizer class and include such a new scheme.
