### ISSUE TITLE
installing the library on ubuntu, documentation

### ISSUE THREAD

**Issue by marvin-ad-martianum** [nicolapiccinelli/libmpc#20]
Amazing library! Thank you. But i was struggling with installing it for a bit. However, i found this sequence of code working amazingly well. 

sudo ./configure.sh 
make
sudo make install

Now im aware that this is quite common, however if you add something like this to the readme in a way or another im sure you could make this code more easily accessible to less professional coders. This package is great! Im from ETH zurich and use it for a ros2 implementation.

**Comment by nicolapiccinelli** [comment]
@marvin-ad-martianum great to hear you are enjoying the lib. IIf you want to contribute open a pull request and update the readme accordingly. Would be very appreciated!

**Comment by nicolapiccinelli** [comment]
@marvin-ad-martianum, see 0.4.1 for the updated `configure.sh` script
