### ISSUE TITLE
Misspelled function name in documentation: `setContinuosTimeModel` should be `setContinuousTimeModel`

### ISSUE THREAD

**Issue by pwintz** [nicolapiccinelli/libmpc#29]
https://altairlab.gitlab.io/optcontrol/libmpc/api/api.html#_CPPv4N3mpc5NLMPC21setContinuosTimeModelEKd

**Comment by nicolapiccinelli** [comment]
If it is misspelt in the documentation, it is also in the source code. There's an update coming in the following weeks. I will manage it.

**Comment by nicolapiccinelli** [comment]
Resolved in 0.5.0
