### ISSUE TITLE
Example codes

### ISSUE THREAD

**Issue by ZhYGu** [nicolapiccinelli/libmpc#4]
Is there any example codes I can test whether I have rightly set up the lib and its dependences? Additionally, I also want learn how to use this lib.

**Comment by nicolapiccinelli** [comment]
Hello @ZhYGu you can look into the tests folder. To check if your dependencies are correctly installed you compile `libmpc++` with debug flag `cmake -DCMAKE_BUILD_TYPE=Debug` and see if the tests run correctly.
